cd /Applications/Sketch.app/Contents/Resources;
xurl='https://raw.githubusercontent.com/nathco/Graphite-UI/master/Graphite/v40'
curl -O $xurl/align_bottom_alt.tiff &
curl -O $xurl/align_bottom.tiff &
curl -O $xurl/align_horizontally_alt.tiff &
curl -O $xurl/align_horizontally.tiff &
curl -O $xurl/align_left_alt.tiff &
curl -O $xurl/align_left.tiff &
curl -O $xurl/align_right_alt.tiff &
curl -O $xurl/align_right.tiff &
curl -O $xurl/align_top_alt.tiff &
curl -O $xurl/align_top.tiff &
curl -O $xurl/align_vertically_alt.tiff &
curl -O $xurl/align_vertically.tiff &
curl -O $xurl/arrowshape24.tiff &
curl -O $xurl/artboard24.tiff &
curl -O $xurl/bitmap_selection.tiff &
curl -O $xurl/bitmap_wand.tiff &
curl -O $xurl/colormenu24.tiff &
curl -O $xurl/combine24.tiff &
curl -O $xurl/create-grid24.tiff &
curl -O $xurl/create-symbol24.tiff &
curl -O $xurl/difference24.tiff &
curl -O $xurl/distribute_horizontally.tiff &
curl -O $xurl/distribute_vertically.tiff &
curl -O $xurl/edit-text24.tiff &
curl -O $xurl/edit-text32.tiff &
curl -O $xurl/edit24.tiff &
curl -O $xurl/editbitmap24.tiff &
curl -O $xurl/export24.tiff &
curl -O $xurl/flatten24.tiff &
curl -O $xurl/fontmenu24.tiff &
curl -O $xurl/grid-layout24.tiff &
curl -O $xurl/grid-square24.tiff &
curl -O $xurl/group24.tiff &
curl -O $xurl/insert-symbol24.tiff &
curl -O $xurl/insert-textstyle24.tiff &
curl -O $xurl/insertimage24.tiff &
curl -O $xurl/insertmenu24.tiff &
curl -O $xurl/insertslice24.tiff &
curl -O $xurl/inserttextlayer24.tiff &
curl -O $xurl/insertvector24.tiff &
curl -O $xurl/inspector_flip_horizontal_pressed.tiff &
curl -O $xurl/inspector_flip_horizontal.tiff &
curl -O $xurl/inspector_flip_vertical_pressed.tiff &
curl -O $xurl/inspector_flip_vertical.tiff &
curl -O $xurl/intersect24.tiff &
curl -O $xurl/iosconnect-disconnected24.tiff &
curl -O $xurl/lineshape24.tiff &
curl -O $xurl/maskwithshape24.tiff &
curl -O $xurl/movebackward24.tiff &
curl -O $xurl/moveforward24.tiff &
curl -O $xurl/ovalshape24.tiff &
curl -O $xurl/pencil24.tiff &
curl -O $xurl/pixeloff24.tiff &
curl -O $xurl/pixelon24.tiff &
curl -O $xurl/polygonshape24.tiff &
curl -O $xurl/prefs_canvas.tiff &
curl -O $xurl/prefs_cloud.tiff &
curl -O $xurl/prefs_general.tiff &
curl -O $xurl/prefs_layers.tiff &
curl -O $xurl/prefs_plugin.tiff &
curl -O $xurl/rectangleshape24.tiff &
curl -O $xurl/rotate24.tiff &
curl -O $xurl/round-nearest24.tiff &
curl -O $xurl/roundrectangleshape24.tiff &
curl -O $xurl/rulers24.tiff &
curl -O $xurl/scale_origin_selected_pressed.tiff &
curl -O $xurl/scale_origin_selected.tiff &
curl -O $xurl/scale24.tiff &
curl -O $xurl/scissors24.tiff &
curl -O $xurl/shape24.tiff &
curl -O $xurl/smartrotate24.tiff &
curl -O $xurl/starshape24.tiff &
curl -O $xurl/subtract24.tiff &
curl -O $xurl/toolbar-zoom-in24.tiff &
curl -O $xurl/toolbar-zoom-out24.tiff &
curl -O $xurl/toolsmenu24.tiff &
curl -O $xurl/transform24.tiff &
curl -O $xurl/triangleshape24.tiff &
curl -O $xurl/ungroup24.tiff &
curl -O $xurl/union24.tiff &
curl -O $xurl/upload-0-24.tiff &
curl -O $xurl/upload-1-24.tiff &
curl -O $xurl/upload-2-24.tiff &
curl -O $xurl/upload-3-24.tiff &
curl -O $xurl/upload-4-24.tiff &
curl -O $xurl/upload-5-24.tiff &
curl -O $xurl/upload-6-24.tiff &
curl -O $xurl/upload-7-24.tiff &
curl -O $xurl/upload-8-24.tiff &
curl -O $xurl/upload-9-24.tiff &
curl -O $xurl/upload24.tiff &
curl -O $xurl/vector_asymmetric.tiff &
curl -O $xurl/vector_disconnected.tiff &
curl -O $xurl/vector_mirrored.tiff &
curl -O $xurl/vector_straight.tiff &
curl -O $xurl/vectorize-stroke24.tiff &
curl -O $xurl/vectorize-text24.tiff &
curl -O $xurl/viewmenu24.tiff &
curl -O $xurl/zoom24.tiff;

afplay /System/Library/Sounds/Glass.aiff